---
title: "Multiple_Regression"
author: "hp621@Scarletmail.rutgers.edu"
date: "2024-11-04"
output: html_document
---

```{r}
library(readr)
library(GGally)
library(MASS)
library(car)
Spotify_Youtube <- read_csv("C:/Users/HARSH/Desktop/RU/SEM 2/MVA/Spotify_Youtube.csv")
```
```{r}
Spotify_Youtube <- as.data.frame(Spotify_Youtube)

dependent_columns <- c(6,8:18, 22:24, 28)

Spotify_Youtube_new<- Spotify_Youtube[, dependent_columns]

Spotify_Youtube_new

str(Spotify_Youtube_new)
```


```{r}
#Data cleaning
Spotify_Youtube_new[!complete.cases(Spotify_Youtube_new), ]

sapply(Spotify_Youtube_new, function(x) mean(is.na(x)) * 100)

Spotify_Youtube_new <- na.omit(Spotify_Youtube_new)
```
```{r}
sampled_data <- Spotify_Youtube_new[sample(nrow(Spotify_Youtube_new), 100), ]

str(sampled_data)
scale(sampled_data)


fit <- lm(Stream~Views+Likes+Comments, data = sampled_data)

summary(fit)
```
```{r}
coefficients(fit)
```

```{r}
ggpairs(data=sampled_data, title="Music Data")
confint(fit,level=0.95)
fitted(fit)
residuals(fit)
```

```{r}
residuals(fit)
#Anova Table
anova(fit)
vcov(fit)
cov2cor(vcov(fit))
temp <- influence.measures(fit)
temp
plot(fit)
```
```{r}

# Global test of model assumptions
library(gvlma)

gvmodel <- gvlma(fit)
summary(gvmodel)
fit
summary(fit)
fit1 <- fit
fit2 <- lm(Stream ~ Likes + Comments , data = sampled_data)
```


```{r}
# compare models
anova(fit1, fit2)

step <- stepAIC(fit, direction="both")
step$anova # display results
```
```{r}
library(leaps)
leaps<-regsubsets(Stream~Likes+Views+Comments,data=sampled_data,nbest=10)
leaps
# view results
plot(leaps)
plot(leaps,scale="r2")
plot(leaps,scale="bic")
summary(leaps)
```
```{r}
library(relaimpo)
calc.relimp(fit,type=c("lmg","last","first","pratt"),
            rela=TRUE)
```

```{r}
summary(fit)
predict.lm(fit, data.frame(Likes=100 ,Comments=20,Views=2000) )

```

